"""Lemonade-Sec detection rules — a starter SAST rule set across web2 + web3.
Each rule: id, name, severity, cwe, langs (file extensions or ['*']), pattern (regex),
desc, fix. Regex is matched per-line (IGNORECASE). This is the extensible core —
add rules freely. Rules flag *candidate* issues for local-LLM/human verification, not proof.
"""

RULES = [
    # ---------- secrets ----------
    dict(id="SEC-AWS", name="Hardcoded AWS access key", severity="high", cwe="CWE-798",
         langs=["*"], pattern=r"AKIA[0-9A-Z]{16}",
         desc="An AWS access key ID appears hardcoded in source.",
         fix="Move to a secrets manager / env var; rotate the exposed key immediately."),
    dict(id="SEC-PRIVKEY", name="Private key material in source", severity="critical", cwe="CWE-798",
         langs=["*"], pattern=r"-----BEGIN (RSA |EC |OPENSSH |DSA |PGP )?PRIVATE KEY-----",
         desc="A private key block is embedded in the repository.",
         fix="Remove from VCS history, rotate the key, store in a secret store."),
    dict(id="SEC-GENERIC", name="Hardcoded credential/secret", severity="medium", cwe="CWE-798",
         langs=["*"], pattern=r"(?i)(password|passwd|api[_-]?key|secret|token)\s*[:=]\s*['\"][^'\"]{6,}['\"]",
         desc="A password/API key/secret appears assigned a literal string value.",
         fix="Load secrets from environment/secret manager, never commit literals."),
    # ---------- injection ----------
    dict(id="INJ-CMD-PY", name="OS command injection (shell=True / os.system)", severity="high", cwe="CWE-78",
         langs=[".py"], pattern=r"(os\.system\(|subprocess\.(Popen|call|run)\([^)]*shell\s*=\s*True)",
         desc="A shell command is built from potentially untrusted input.",
         fix="Use argument lists (shell=False); never interpolate user input into a shell string."),
    dict(id="INJ-EVAL", name="Dangerous dynamic eval/exec", severity="high", cwe="CWE-95",
         langs=[".py", ".js", ".ts", ".php", ".rb"], pattern=r"(?<![\w.])(eval|exec)\s*\(",
         desc="Dynamic code execution on possibly untrusted input.",
         fix="Remove eval/exec; use safe parsers / explicit dispatch."),
    dict(id="INJ-SQL", name="Possible SQL injection (string-built query)", severity="high", cwe="CWE-89",
         langs=[".py", ".js", ".ts", ".php", ".java", ".go"],
         pattern=r"(?i)(select|insert|update|delete)\s+.*\+\s*[a-zA-Z_]\w*",
         desc="A SQL statement is concatenated with a variable.",
         fix="Use parameterized queries / prepared statements."),
    dict(id="INJ-DESERIAL", name="Unsafe deserialization", severity="high", cwe="CWE-502",
         langs=[".py"], pattern=r"(pickle\.loads?\(|yaml\.load\((?![^)]*Loader)|marshal\.loads?\()",
         desc="Deserializing untrusted data can lead to RCE.",
         fix="Use yaml.safe_load / json; never unpickle untrusted bytes."),
    # ---------- ssrf / traversal / xss ----------
    dict(id="SSRF", name="Possible SSRF (request to variable URL)", severity="medium", cwe="CWE-918",
         langs=[".py", ".js", ".ts", ".go"],
         pattern=r"(requests\.(get|post|put)\(|urllib\.request\.urlopen\(|fetch\(|axios\.(get|post)\()\s*[a-zA-Z_]\w*",
         desc="An outbound HTTP request targets a non-literal URL — check for user control.",
         fix="Allow-list destinations; block internal ranges (169.254/10/127/metadata)."),
    dict(id="PATH-TRAVERSAL", name="Path built from request input", severity="medium", cwe="CWE-22",
         langs=[".py", ".js", ".ts"], pattern=r"open\([^)]*(request|req|params|input|argv)[^)]*\)",
         desc="A file path may include user input — potential traversal.",
         fix="Canonicalize + confine to a base dir; reject '..'."),
    dict(id="XSS-DOM", name="DOM XSS sink", severity="medium", cwe="CWE-79",
         langs=[".js", ".ts", ".jsx", ".tsx", ".html"],
         pattern=r"(\.innerHTML\s*=|dangerouslySetInnerHTML|document\.write\()",
         desc="Untrusted data written to an HTML sink can execute script.",
         fix="Use textContent / framework escaping / DOMPurify."),
    # ---------- crypto / config ----------
    dict(id="CRY-WEAK-HASH", name="Weak hash for security use", severity="medium", cwe="CWE-327",
         langs=["*"], pattern=r"(?i)(md5|sha1)\s*\(",
         desc="MD5/SHA1 are unsuitable for passwords/signatures.",
         fix="Use SHA-256+ for integrity; bcrypt/argon2/scrypt for passwords."),
    dict(id="CRY-RANDOM", name="Insecure randomness for security token", severity="medium", cwe="CWE-338",
         langs=[".py", ".js", ".ts"], pattern=r"(Math\.random\(\)|random\.random\(\)|random\.randint\()",
         desc="Non-CSPRNG used where unpredictability may be required.",
         fix="Use secrets (py) / crypto.getRandomValues (js)."),
    dict(id="CFG-TLS-VERIFY", name="TLS verification disabled", severity="high", cwe="CWE-295",
         langs=["*"], pattern=r"(verify\s*=\s*False|rejectUnauthorized\s*:\s*false|InsecureSkipVerify\s*:\s*true)",
         desc="Certificate validation is disabled — MITM risk.",
         fix="Enable verification; pin/trust the correct CA."),
    dict(id="CFG-DEBUG", name="Debug mode enabled", severity="medium", cwe="CWE-489",
         langs=[".py"], pattern=r"(?i)debug\s*=\s*True",
         desc="Framework debug mode can leak stack traces / enable RCE consoles.",
         fix="Disable debug in production."),
    dict(id="CFG-CORS", name="Permissive CORS wildcard", severity="medium", cwe="CWE-942",
         langs=["*"], pattern=r"Access-Control-Allow-Origin['\"]?\s*[:,]\s*['\"]\*",
         desc="Wildcard CORS with credentials can leak authenticated data.",
         fix="Reflect an allow-listed origin; avoid '*' with credentials."),
    dict(id="AUTH-JWT-NONE", name="JWT 'none' algorithm accepted", severity="high", cwe="CWE-347",
         langs=["*"], pattern=r"(?i)alg['\"]?\s*[:=]\s*['\"]none['\"]",
         desc="Accepting alg=none lets attackers forge tokens.",
         fix="Pin expected algorithm; reject 'none'."),
    # ---------- web3 / solidity ----------
    dict(id="SOL-TXORIGIN", name="tx.origin used for authorization", severity="high", cwe="CWE-284",
         langs=[".sol"], pattern=r"tx\.origin",
         desc="tx.origin auth is phishable via intermediary contracts.",
         fix="Use msg.sender for authorization."),
    dict(id="SOL-LOWCALL", name="Unchecked low-level call", severity="high", cwe="CWE-252",
         langs=[".sol"], pattern=r"\.(call|delegatecall|send)\s*(\{[^}]*\})?\s*\(",
         desc="Low-level call return value may be unchecked; delegatecall to untrusted target is critical.",
         fix="Check return value; avoid delegatecall to user-controlled addresses; prefer transfer/checks."),
    dict(id="SOL-REENTRANCY", name="External call before state update (reentrancy)", severity="critical", cwe="CWE-841",
         langs=[".sol"], pattern=r"\.call\{value:",
         desc="Value-sending external call — verify state is updated BEFORE it (checks-effects-interactions).",
         fix="Apply checks-effects-interactions and/or a nonReentrant guard."),
    dict(id="SOL-SELFDESTRUCT", name="selfdestruct present", severity="high", cwe="CWE-284",
         langs=[".sol"], pattern=r"selfdestruct\s*\(",
         desc="selfdestruct can brick a contract / force-send ETH; verify access control.",
         fix="Guard with strict access control or remove."),
    dict(id="SOL-TIMESTAMP", name="block.timestamp used as randomness", severity="medium", cwe="CWE-330",
         langs=[".sol"], pattern=r"(block\.timestamp|block\.number|blockhash)\b.*(random|rand|seed|winner|lottery)",
         desc="Miner/validator-influenceable values used for randomness.",
         fix="Use a VRF (e.g. Chainlink VRF) or commit-reveal."),
    dict(id="SOL-PRAGMA", name="Floating/old pragma", severity="low", cwe="CWE-1104",
         langs=[".sol"], pattern=r"pragma solidity\s*\^?0\.[1-7]\.",
         desc="Old or unpinned compiler version may carry known bugs.",
         fix="Pin a current, audited compiler version."),
    dict(id="SOL-ARBDELEGATE", name="delegatecall (possible arbitrary target)", severity="critical",
         cwe="CWE-829", langs=[".sol"], pattern=r"delegatecall\s*\(",
         desc="delegatecall runs external code in this contract's storage/context; a user-controlled target = full takeover.",
         fix="Never delegatecall to user-controlled addresses; use a fixed, audited library."),
    # ---------- more secrets ----------
    dict(id="SEC-GOOGLE", name="Google API key", severity="high", cwe="CWE-798", langs=["*"],
         pattern=r"AIza[0-9A-Za-z\-_]{35}", desc="A Google API key appears hardcoded.",
         fix="Restrict + rotate the key; store server-side."),
    dict(id="SEC-STRIPE", name="Stripe live secret key", severity="critical", cwe="CWE-798", langs=["*"],
         pattern=r"sk_live_[0-9A-Za-z]{16,}", desc="A live Stripe secret key is exposed.",
         fix="Rotate immediately; never ship secret keys client-side."),
    dict(id="SEC-GITHUB", name="GitHub token", severity="high", cwe="CWE-798", langs=["*"],
         pattern=r"gh[posur]_[0-9A-Za-z]{36,}", desc="A GitHub personal/OAuth token is exposed.",
         fix="Revoke + rotate; use short-lived tokens / secret store."),
    dict(id="SEC-SLACK", name="Slack token", severity="high", cwe="CWE-798", langs=["*"],
         pattern=r"xox[baprs]-[0-9A-Za-z-]{10,}", desc="A Slack token is exposed.",
         fix="Revoke + rotate."),
    # ---------- more web ----------
    dict(id="WEB-JWT-NOVERIFY", name="JWT decoded without verification", severity="high", cwe="CWE-347",
         langs=[".py", ".js", ".ts"], pattern=r"jwt\.decode\([^)]*verify\s*=\s*False",
         desc="Token accepted without signature verification — forgeable.",
         fix="Verify the signature with a pinned algorithm; reject unverified tokens."),
    dict(id="WEB-SSTI", name="Server-side template injection sink", severity="high", cwe="CWE-1336",
         langs=[".py", ".js", ".ts"],
         pattern=r"(render_template_string\(|Template\([^)]*(request|req|params|input)|\.render\([^)]*(request|req))",
         desc="User input flows into a template engine — can lead to RCE.",
         fix="Never build templates from user input; pass data as sandboxed variables."),
    dict(id="WEB-XXE", name="XML parsing (possible XXE)", severity="medium", cwe="CWE-611",
         langs=[".py", ".java", ".php"],
         pattern=r"(etree\.(parse|fromstring)\(|DocumentBuilderFactory|SAXParser|simplexml_load)",
         desc="XML parsed without explicitly disabling external entities → XXE/SSRF/file read.",
         fix="Disable DTD/external entities (defusedxml / secure parser features)."),
    dict(id="WEB-OPENREDIRECT", name="Open redirect", severity="medium", cwe="CWE-601",
         langs=[".py", ".js", ".ts"],
         pattern=r"(redirect\(|res\.redirect\(|location\.href\s*=)\s*[^)]*(request|req|params|query|next|url)",
         desc="Redirect target derived from user input — phishing/token leak.",
         fix="Allow-list redirect destinations; use relative paths / mapping keys."),
    dict(id="WEB-MASSASSIGN", name="Mass assignment", severity="medium", cwe="CWE-915",
         langs=[".py", ".js", ".ts"],
         pattern=r"(\.update\(\s*\*\*?request|Object\.assign\([^,]+,\s*req\.body|\.create\(\s*\*\*?request|new\s+\w+\(req\.body\))",
         desc="Object populated directly from request body — attacker can set unintended fields (role/owner).",
         fix="Bind only an explicit allow-list of fields."),
    dict(id="WEB-IDOR-HINT", name="Object fetched by client-supplied id", severity="low", cwe="CWE-639",
         langs=[".py", ".js", ".ts"],
         pattern=r"(get_object_or_404|findById|findOne|\.get\()\s*\([^)]*(request|req|params|query)\.[\w\[\]'\"]*id",
         desc="Object loaded by a user-supplied id — verify an ownership/authorization check exists.",
         fix="Enforce object-level authorization: object.owner == current_user."),
    dict(id="JS-PROTOPOLLUTION", name="Prototype pollution sink", severity="medium", cwe="CWE-1321",
         langs=[".js", ".ts"], pattern=r"(__proto__|constructor\s*\[\s*['\"]prototype|\.prototype\s*\[)",
         desc="Recursive merge/assign into __proto__ can pollute Object.prototype.",
         fix="Use Map / null-proto objects; block __proto__/constructor keys; freeze prototypes."),
    dict(id="WEB-REDOS", name="Potential ReDoS regex", severity="low", cwe="CWE-1333",
         langs=[".py", ".js", ".ts"],
         pattern=r"(\(\.\*\)\+|\(\.\+\)\+|\(\\w\+\)\+|\(\[\^.\]\+\)\+)",
         desc="Nested quantifier can cause catastrophic backtracking on crafted input.",
         fix="Simplify the regex; use possessive/atomic groups or a linear engine (re2)."),
]
